#include <stdio.h> //printf() 함수를 사용하기 위한 헤더 파일 포함 
#include <conio.h> //_getch() 함수를 사용하기 위한 헤더 파일 포함 
#include <windows.h> //system() 함수를 사용하기 위한 헤더 파일 포함 
int main(void)
{
	char ch=0;
	
	printf("아무키나 누르면 다음으로 넘어가요^^ \n");
	ch=_getch();
	system("cls");
	printf("준하에게.\n\n");
	printf("아무키나 누르면 다음으로 넘어가요^^ \n");
	ch=_getch();
	system("cls");
	printf("안녕!! 나 영동이야^^\n\n");
	printf("아무키나 누르면 다음으로 넘어가요^^ \n");
	ch=_getch();
	system("cls");
	printf("일단은 내가 너의 멘티가 될 수 있어서 정말로 영광이야.\n\n");
	printf("아무키나 누르면 다음으로 넘어가요^^ \n");
	ch=_getch();
	system("cls");
	printf("내가 프로그래밍을 잘하지 못해서 계속 힘들어 할때\n\n");
	printf("아무키나 누르면 다음으로 넘어가요^^ \n");
	ch=_getch();
	system("cls");
	printf("내가 포기하지 않게 끝까지 도움을 줘서 정말로 고마워.\n\n");
	printf("아무키나 누르면 다음으로 넘어가요^^ \n");
	ch=_getch();
	system("cls");
	printf("만약 내가 너였다면 분명 너 처럼 친구가 모르는 것에 대해.\n\n");
	printf("아무키나 누르면 다음으로 넘어가요^^ \n");
	ch=_getch();
	system("cls");
	printf("관심을 가지며 잘 알려주지는 못했을거야.\n\n");
	printf("아무키나 누르면 다음으로 넘어가요^^ \n");
	ch=_getch();
	system("cls");
	printf("처음 이 학교에 와서 프로그래밍 수업을 할때\n\n");
	printf("아무키나 누르면 다음으로 넘어가요^^ \n");
	ch=_getch();
	system("cls");
	printf("프로그래밍에 대해 전혀 아는 것이 없어서\n\n");
	printf("아무키나 누르면 다음으로 넘어가요^^ \n");
	ch=_getch();
	system("cls");
	printf("내가 과연 이학교 다니면 수업을 잘 따라갈 수 있을지 매우 걱정했어.\n\n");
	printf("아무키나 누르면 다음으로 넘어가요^^ \n");
	ch=_getch();
	system("cls");
	printf("그런데 너 덕뿐에 이러한 걱정을 덜수 있게 되었어.\n\n");
	printf("아무키나 누르면 다음으로 넘어가요^^ \n");
	ch=_getch();
	system("cls");
	printf("정말로 고마워.\n\n");
	printf("아무키나 누르면 다음으로 넘어가요^^ \n");
	ch=_getch();
	system("cls");
	printf("준하야.\n\n");
	printf("아무키나 누르면 다음으로 넘어가요^^ \n");
	ch=_getch();
	system("cls");
	printf("그럼\n\n");
	printf("아무키나 누르면 다음으로 넘어가요^^ \n");
	ch=_getch();
	system("cls");
	printf("앞으로도 같이 학교 생활하며 같이 잘 지내자^^\n\n");
	printf("아무키나 누르면 다음으로 넘어가요^^ \n");
	ch=_getch();
	system("cls");
	printf("준하야 정말로 고마워!!!.\n\n");
	printf("아무키나 누르면 다음으로 넘어가요^^ \n");
	ch=_getch();
	system("cls");
	printf("2017년 3월 21일\n\n");
	printf("아무키나 누르면 다음으로 넘어가요^^ \n");
	ch=_getch();
	system("cls");
	printf("너의 친구이자 멘티\n\n");
	printf("아무키나 누르면 다음으로 넘어가요^^ \n");
	ch=_getch();
	system("cls");
	printf("영동이가\n\n");
	system("pause");
	return 0;
}
